site_name: "Better Step"
site_url: "https://better-step.github.io"
theme:
  name: "material"
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API:
      - Overview: hdf5_mesh_sampler.md
      - Geometry: api/geometry.md
      - Topology: api/topology.md
      - Sampling: api/sampling.md
      - Visualization: api/visualization.md
  - Examples: examples/intro.ipynb
  - FAQ: faq.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Authors: AUTHORS.rst
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys; sys.path.insert(0, 'hdf5_mesh_sampler')

